apiVersion: v1
kind: Service
metadata:
  name: pet-tracker-frontend
  namespace: pet-tracker
spec:
  selector:
    app: pet-tracker-frontend
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080
